version: "3.9"

services:
  api:
    build:
      context: .
      args:
          - "ENV=development"
    env_file:
      - .env.docker
    image: freelancer-api:dev
    container_name: freelancer-api
    restart: unless-stopped
    depends_on:
      - mysql-db
      - redis
    volumes:
      - ".:/var/www/html"
      - "/var/www/html/.docker"
      - "/var/www/html/.git"
      - "/var/www/html/.idea"
      - "/var/www/html/.vscode"
    ports:
      - "8080:8080"
    networks:
      - backend

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=RUBZ+NdoIb+cD8Lh3l1Nj3p"
      - "MYSQL_PASSWORD=An0thrS3crt"
      - "MYSQL_USER=freelancer_user"
      - "MYSQL_DATABASE=jlwai+JBnCasdZlVtWj3"
    volumes:
        - 'mysql-storage:/var/lib/mysql'
    ports:
      - "3306:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-freelancer
    restart: unless-stopped
    depends_on:
      - mysql-db
    ports:
     - "20082:80"
    environment:
      - "PMA_HOST=mariadb-bootstrap"
      - "PMA_USER=freelancer_user"
      - "PMA_PASSWORD=jlwai+JBnCasdZlVtWj3"
    networks:
      - backend

  redis:
    image: redis:latest
    environment:
        TZ: Asia/Ho_Chi_Minh
    volumes:
        - 'redis-storage:/data'
    networks:
        - backend
    healthcheck:
        test: [ 'CMD', 'redis-cli', 'ping' ]
        retries: 3
        timeout: 5s

networks:
  backend:
    name: wheel-network
    driver: bridge

volumes:
    mysql-storage:
        driver: local
    redis-storage:
        driver: local
