version: "3.9"

services:
  api:
    build:
      context: .
      args:
          - "ENV=development"
    env_file:
      - .env
    image: recuilt-api:dev
    container_name: recuilt-api
    restart: unless-stopped
    depends_on:
      - mysql-db
      - redis
    ports:
      - "80:8080"
    networks:
      - backend

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    volumes:
        - '~/data/db:/var/lib/mysql'
    ports:
      - "3306:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-recuilt
    restart: unless-stopped
    depends_on:
      - mysql-db
    ports:
     - "20082:80"
    environment:
      - "PMA_HOST=mysql-db"
      - "PMA_USER=${DB_USERNAME}"
      - "PMA_PASSWORD=${DB_PASSWORD}"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis-recuilt
    environment:
        TZ: Asia/Ho_Chi_Minh
    volumes:
        - 'redis-storage:/data'
    networks:
        - backend
    healthcheck:
        test: [ 'CMD', 'redis-cli', 'ping' ]
        retries: 3
        timeout: 5s

networks:
  backend:
    name: recuilt-network
    driver: bridge

volumes:
    mysql-storage:
        driver: local
    redis-storage:
        driver: local
